# Server
server.port=8080

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Application Info
info.app.name=Spring Blackjack
info.app.description=A 1-on-1 Blackjack game built with Spring Boot
info.app.version=@project.version@
